### ISSUE TITLE
export redis list instead of queue and cannot export data in grafana dashboard

### ISSUE THREAD

**Issue by palsonkansakar09** [ashishtiwari1993/redis_queue_length_exporter#1]
export redis list instead of queue and cannot export data in grafana dashboard.
- redis hosts is not shown in grafana

**Comment by ashishtiwari1993** [comment]
Hey Palsonkan,

Can you try with with below Grafana dashboard:
https://grafana.com/grafana/dashboards/10287

**Comment by palsonkansakar** [comment]
yes i did use the above dashboard

**Comment by ashishtiwari1993** [comment]
I verified on my local. Its working fine.

![grafana-redis-queue-length](https://user-images.githubusercontent.com/19850674/91451875-88262e80-e89b-11ea-87e8-9eaa75271ed5.png)

Can you hit below prometheus url:
http://localhost:9090/metrics

Search for text `redis_llen_exporter`.

You should get below metrics:
```sh
net_conntrack_dialer_conn_failed_total{dialer_name="redis_llen_exporter",reason="refused"} 0
net_conntrack_dialer_conn_failed_total{dialer_name="redis_llen_exporter",reason="resolution"} 0
net_conntrack_dialer_conn_failed_total{dialer_name="redis_llen_exporter",reason="timeout"} 0
net_conntrack_dialer_conn_failed_total{dialer_name="redis_llen_exporter",reason="unknown"} 0
```

`refused` should be `0`. 

I Just want to confirm whether Prometheus is successfully polling or not.

**Comment by ashishtiwari1993** [comment]
Continued on this thread 
https://github.com/ashishtiwari1993/redis_queue_length_exporter/issues/2
