### ISSUE TITLE
Redis Authentication Option

### ISSUE THREAD

**Issue by McGuywer** [ashishtiwari1993/redis_queue_length_exporter#3]
Hallo,
Do you have a config option where I can set the Redis password for authentication?
Thank you.

**Comment by ashishtiwari1993** [comment]
As suggested here https://redislabs.com/lp/python-redis/, You can edit `llen.py` like below:
```python
import redis

r = redis.Redis(
host='hostname',
port=port,
password='password')
```

**Comment by McGuywer** [comment]
Thank you @ashishtiwari1993
